name: CI React (Create React App) a master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instal·la dependències
        run: npm ci

      - name: Compila el projecte
        run: npm run build
